[versions]
activityCompose = "1.10.1"
anhance = "2025.3.0"
appcompat = "1.7.0"
composeBom = "2025.03.00"
constraintlayout = "1.1.1"
coreKtx = "1.15.0"
coreSplashscreen = "1.0.1"
espressoCore = "3.6.1"
hiltNavigation = "1.2.0"
hiltVersion = "2.51.1"
junit = "4.13.2"
junitVersion = "1.2.1"
navigationCompose = "2.8.9"
serialization = "1.8.0"
modify = "0.1.2"

# plugin
kotlin = "2.1.0"
agp = "8.9.0"
ksp = "2.1.0-1.0.29"
hilt = "2.51.1"


[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-graphic = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigation" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
google-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltVersion" }
google-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltVersion" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
naulian-anhance = { module = "com.naulian:anhance", version.ref = "anhance" }
naulian-modify = { module = "com.naulian:modify", version.ref = "modify" }


[plugins]
application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }





